### ISSUE TITLE
Don't allow refresh of expired token

### ISSUE THREAD

**Issue by Joebayld** [LiveUI/ApiCore#18]
Hi, 

Shouldn't the refresh token route not pass if the token is expired? I was thinking the following in the AuthController.token route: 

`
           if token.expires < Date() {
                throw AuthError.tokenExpired
            }
`

**Comment by rafiki270** [comment]
Looks like I forgot that one :) ... or possibly created the expiration column so I don’t forget later, not sure anymore

Either way, it should check the expiration and if invalid, it should delete the old token from db!

**Comment by rafiki270** [comment]
implemented in RC2.2
